CREATE DATABASE IF NOT EXISTS costomer_behavior;
USE costomer_behavior;

show tables;

select * from customer_behavior_data limit 10;

-- Q1.What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as total_revenue
FROM customer_behavior_data
GROUP BY gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id , discount_applied , purchase_amount
FROM customer_behavior_data 
WHERE discount_applied ='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior_data
);

-- Q3.Which are the top 5 products with the highest average review rating?
SELECT item_purchased , AVG(review_rating) AS "avg_review_rating"
FROM customer_behavior_data 
GROUP BY item_purchased
ORDER BY AVG(review_rating)DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amount
FROM customer_behavior_data 
WHERE shipping_type in ("Standard" ,"Express")
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT COUNT(customer_id) AS total_customer,
subscription_status, 
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM  customer_behavior_data
GROUP BY subscription_status;

-- 06. Which 5 products have the highest percentage of purchases with discounts applied?.
SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100,2) AS discount_rate
FROM customer_behavior_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT COUNT(customer_id), 
CASE WHEN previous_purchases = 1 THEN "New"
     WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
     WHEN previous_purchases > 10 THEN "Loyal"
     END AS customer_segment
FROM customer_behavior_data    
GROUP BY customer_segment ;

-- Q8. What are the top 3 most purchased products within each category

with item_counts as (
select category, item_purchased,
COUNT (customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank 
from customer_behavior_data
group by category,item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts 
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_behavior_data  
WHERE previous_purchases > 5
GROUP BY subscription_status ;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_behavior_data
GROUP BY age_group
ORDER BY total_revenue DESC ;
